### ISSUE TITLE
Error when searching for a person without a birth date

### ISSUE THREAD

**Issue by ennoborg** [jmichault/PersonFS#10]
I just found a person who has a birth event with a place, but no data, and for that person, clicking the Search button generated the error below:

1643009: ERROR: grampsapp.py: line 173: Unhandled exception
Traceback (most recent call last):
  File "/home/enno/.gramps/gramps51/plugins/PersonFS/PersonFS.py", line 767, in ButSercxi_clicked
    if birdoDato[0] == 'A' : birdoDato = birdoDato[1:]
IndexError: string index out of range

**Comment by jmichault** [comment]
Fixed in release 1.3.2.
Can you test and confirm the fix?
