### ISSUE TITLE
FS date before is stored as a range starting at year zero

### ISSUE THREAD

**Issue by ennoborg** [jmichault/PersonFS#11]
When I import this ancestor from FamilySearch

https://www.familysearch.org/tree/person/details/KZCP-RPL

his death date, which is described as BEF 1724 is imported as a range between 0000-00-00 and 1724-00-00, which confuses Gramps, and can even lead to an error, because Gramps doesn't expect this format. The error is described here

https://gramps-project.org/bugs/view.php?id=12865

and only appears in event view. And even when this is fixed, editing the person does not show his death date as before 1724.

Please make sure that the date is saved in the proper format, just as it would appear when I do an import with Ancestral Quest or RootsMagic, and import that GEDCOM into Gramps.

**Comment by jmichault** [comment]
Can you test with v1.4.2 ?

**Comment by ennoborg** [comment]
I tried it in an empty database, importing two parent generations from his son, not knowing if the generation cound it inclusive, and ran into the following error:

2023-04-11 17:52:00.761: ERROR: grampsapp.py: line 173: Unhandled exception
Traceback (most recent call last):
  File "/home/enno/gramps/gramps/gui/plug/_windows.py", line 807, in on_ok_clicked
    self.run() # activate results tab
  File "/home/enno/.gramps/gramps51/plugins/PersonFS/Importo.py", line 866, in run
    importilo.importi(self,self.FS_ID)
  File "/home/enno/.gramps/gramps51/plugins/PersonFS/Importo.py", line 502, in importi
    print( _("Elŝutante %s generaciojn de ascendantojn…") % (i + 1))
ValueError: unsupported format character 'S' (0x53) at index 20

And then I found two print lines where you used that S for an integer, and changed %s to %d, and that worked. And with that patch, the import worked too, and the before date is now imported right.
