### ISSUE TITLE
Error message shown when gedcomx is too old uses gettext, which hasn´t been imported yet.

### ISSUE THREAD

**Issue by ennoborg** [jmichault/PersonFS#15]
When I run the new 1.4.1 it checks the version of your gedcomx package, and when that's too old, it uses gettext to display a message. And this fails, because at that time gettext hasn´t been imported yet.

I tried moving the check to a location after the gettext import, but that triggered two other errors, so I hope that you can find a better fix.

**Comment by jmichault** [comment]
Corrected in 1.4.2.
Can you confirm ?

**Comment by ennoborg** [comment]
Yes. I used pip to uninstall gedcomx-v1, and when I ran gramps from terminal, it printed the message, and installed the right gedcomx package again.
