### ISSUE TITLE
Glade file has Esperanto text that cannot be translated.

### ISSUE THREAD

**Issue by emyoulation** [jmichault/PersonFS#23]
There is  a multi-line label in the Glade file that isn't translating. I wonder if the .po and .mo files are not finding an exact match for translation because of extra linefeeds/carriage returns?

```
Alklakante la Apliki-Butonon, mi konsentas
PersonFS ŝatus scii viajn bazajn FamilySearch-profilinformojn kaj alirdatenojn pri viaj prapatroj de la FamilySearch genealogia arbo.
PersonFS uzos ĉi tiujn informojn konforme al iliaj respektivaj servokondiĉoj kaj privatecaj politikoj.
```

Perhaps reformatting lines 154 through 157 into shorter string will resolve the problem?

See:
https://github.com/jmichault/PersonFS/blob/main/PersonFS.glade#L154-L157

**Comment by jmichault** [comment]
I have corrected locale/traduko.sh.
Additionally, I included the translation in version 1.4.6.
