### ISSUE TITLE
Find and compare multiple surname.

### ISSUE THREAD

**Issue by wQuick** [jmichault/PersonFS#37]
Please fix find and compare person with multiple surname.

![2023-12-25_13-55](https://github.com/jmichault/PersonFS/assets/4439940/7f05d935-aa91-4bb7-aea4-36c9f87f0687)

![2023-12-25_13-56](https://github.com/jmichault/PersonFS/assets/4439940/56fbd01c-7623-4f3c-ae90-a77863dc0965)

**Comment by jmichault** [comment]
fixed in 5.2 release ( <https://github.com/jmichault/gramps-kromprogramoj> )
