### ISSUE TITLE
Trying to use for first time: No module named 'packaging'

### ISSUE THREAD

**Issue by jcarroll** [jmichault/PersonFS#40]
Trying to use gramps for the first time and PersonFS for the first time:

On linux on chromebook (ChromeOS).
Installed gramps via apt

Did this...
```
cd ~/.gramps/gramps51/plugins`
`git clone https://github.com/jmichault/PersonFS.git
```
... per [instructions](https://github.com/jmichault/gramps-kromprogramoj/blob/gramps51/fontoj/PersonFS/README.en.md). 

Verified that "requests" module was installed; also did 
```linuxuser@penguin:~$ pip install gedcomx-v1```

When running, I see the following logs.
```
linuxuser@penguin:~$ gramps 
2024-01-30 20:28:08.742: WARNING: dummydb.py: line 1419: database is closed
2024-01-30 20:28:17.220: WARNING: _manager.py: line 307: Plugin error (from 'PersonFS'): No module named 'packaging'
2024-01-30 20:28:17.221: WARNING: grampletpane.py: line 180: Error loading gramplet 'FS Gramplet': skipping content
/usr/lib/python3/dist-packages/gi/overrides/GObject.py:493: Warning: ../../../gobject/gsignal.c:2732: instance '0x29752260' has no handler with id '23288'
  return func(*args, **kwargs)
```

The one that seems most telling to me is this one:
`Plugin error (from 'PersonFS'): No module named 'packaging'`

Are there more instructions to get started with PersonFS?  Any additional assistance is most welcome.

Thank you kindly,

**Comment by jmichault** [comment]
Hello.
I don't know chrome os.
You can try `sudo apt install python3-packaging`
or ` pip install packaging`

**Comment by jcarroll** [comment]
Thanks so much!  did the `pip` command you recommended; now I'm getting the following:

```
2024-02-13 19:37:39.119: WARNING: dummydb.py: line 1419: database is closed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gramps/gen/plug/_manager.py", line 252, in load_plugin
    _module = self.import_plugin(pdata)
  File "/usr/lib/python3/dist-packages/gramps/gen/plug/_manager.py", line 285, in import_plugin
    module = __import__(pdata.mod_name)
  File "/home/linuxuser/.gramps/gramps51/plugins/PersonFS/PersonFS.py", line 84, in <module>
    import komparo
  File "/home/linuxuser/.gramps/gramps51/plugins/PersonFS/komparo.py", line 49, in <module>
    import utila
  File "/home/linuxuser/.gramps/gramps51/plugins/PersonFS/utila.py", line 146
    match  grObjekto.__class__.__name__ :
           ^
SyntaxError: invalid syntax
2024-02-13 19:39:16.328: WARNING: grampletpane.py: line 180: Error loading gramplet 'FS Gramplet': skipping content
Gdk-Message: 19:39:21.343: Window 0x2a220d20 is a temporary window without parent, application will not be able to position it on screen.

(gramps:732): Gdk-CRITICAL **: 19:39:21.364: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```
Here, I think the crux is this line:
```
SyntaxError: invalid syntax
```
Any recommendations?

**Comment by jmichault** [comment]
You can try to edit file setup.py and change line 35 to:
`from setuptools._distutils import log`

**Comment by jcarroll** [comment]
Thank you, @jmichault for the suggestion.

My chromebook received a Linux system update to Debian 12 (from 11), which comes with Python 3.11:

![Screenshot 2024-02-17 5 05 47 PM](https://github.com/jmichault/PersonFS/assets/293940/5454ec2e-48aa-4d91-82ea-8d8fa30aee7a)

_Aside_: I tried the upgrade, which failed (perhaps because I had a spotty Internet connection, perhaps because I disregarded the warning and installed python3.12 on top of, instead of alongside, the system-provided python3.9. So, I removed Linux and then reinstalled it.

So, with a fresh Linux installation, now running Python3.11, I did the following:

1. ```$ sudo apt install gramps -y```
2. Imported gedcom file
3. Installed personFS via plugin-manager, per [instructions](https://github.com/jmichault/gramps-kromprogramoj/blob/gramps51/fontoj/PersonFS/README.en.md#install)
4. Selected person and tried to enable, per [instructions](https://github.com/jmichault/gramps-kromprogramoj/blob/gramps51/fontoj/PersonFS/README.en.md#enable)

Console output:
```
(gramps:4551): Gdk-CRITICAL **: 18:28:39.522: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
gedcomx_v1 ne trovita aŭ < 1.0.20
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting gedcomx_v1
  Downloading gedcomx_v1-1.0.20-py3-none-any.whl (32 kB)
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 967.8 kB/s eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (136 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.6/136.6 kB 2.0 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.6-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 1.9 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.2.0-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.9/120.9 kB 571.7 kB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 2.3 MB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, gedcomx_v1
  WARNING: The script normalizer is installed in '/home/cabbage/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 gedcomx_v1-1.0.20 idna-3.6 requests-2.31.0 urllib3-2.2.0
WARNING: Plugin error (from 'PersonFS'): No module named 'gedcomx_v1'
WARNING: Error loading gramplet 'FS Gramplet': skipping content
```
(If I understand that output, it means that gramps / personFS automatically installed the missing dependencies.)

After this, the side bar had the "Fs" tab, but it was blank.

5. Closed gramps
6. Opened gramps
7. Entered FamilySearch credentials
8. _viola!_ PersonFS appears to be working!

![Screenshot 2024-02-17 6 39 32 PM](https://github.com/jmichault/PersonFS/assets/293940/6d3bcc03-4d2d-4b00-a7d0-816d204d9a69)
