### ISSUE TITLE
Impossible de lier si un attribut est déjà présent

### ISSUE THREAD

**Issue by olivierberten** [jmichault/PersonFS#9]
Bonjour,

Quand j'essaye de lier un profil par la recherche, j'obtiens le message d'erreur suivant : `maljsonigi:nekonata ero: Person:fields`
Si j'ajoute manuellement l'attribut, la comparaison fonctionne.

Ce qui est bizarre c'est que ça fonctionnait avant mais je n'ai aucune idée de ce que j'ai changé... J'ai essayé plusieurs versions mais le problème reste présent.

**Comment by ennoborg** [comment]
I see that message in terminal a lot, and I can't fnd "nekonata ero" in the source code, so I have no idea what it means.

**Comment by olivierberten** [comment]
The message comes from the gedcomx library: https://github.com/jmichault/gedcomx/blob/6f141a36cc173df4e31fdd16992352c2078dc4df/gedcomx/json.py#L175

**Comment by olivierberten** [comment]
Thanks to @ennoborg https://gramps.discourse.group/t/familysearch-gramplet/3475/28 I realized the linking issue isn't related to the messages. The actual problem is as mentioned in the corrected title.

Comme me l'a fait réaliser Enno Borgsteede sur le forum de Gramps, le problème n'est pas lié aux messages mais au fait que mes individus ont déjà des attributs. Cela fonctionnait avant car je faisais les tests sur un arbre qui n'avait pas d'attributs préalables.

**Comment by jmichault** [comment]
Je reproduis bien le bogue. Je vais travailler dessus.

**Comment by jmichault** [comment]
J'ai publié la version 1.3.2 qui corrige le bogue.

Note : la version sur la branche dev corrige plein d'autres petits bogues, et elle a aussi quelques nouveautés. Par contre elle nécessite de patcher gramps avec la commande : 
`sudo sed -i 's/int(path)/path/' /usr/lib/python3/dist-packages/gramps/gui/listmodel.py`

Du coup j'hésite à la publier.

**Comment by olivierberten** [comment]
Je viens d'ouvrir un rapport de bug chez Gramps pour le ListModel : https://gramps-project.org/bugs/view.php?id=12864

**Comment by olivierberten** [comment]
Le patch sera bientôt appliqué gramps
https://github.com/gramps-project/gramps/pull/1426/
